[package]
name = "calculator-add-simple-server"
version = "0.2.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0"

turul-mcp-server = { path = "../../crates/turul-mcp-server" }
turul-mcp-derive = { path = "../../crates/turul-mcp-derive" }
turul-mcp-protocol = { path = "../../crates/turul-mcp-protocol" }
http-turul-mcp-server = { path = "../../crates/http-turul-mcp-server" }