[package]
name = "spec-compliant-server"
version = "0.2.2"
edition.workspace = true

[dependencies]
turul-mcp-derive = { workspace = true }
turul-mcp-server = { workspace = true }
turul-mcp-protocol = { workspace = true }
turul-mcp-protocol-2025-06-18 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }