[package]
name = "simple-postgres-session"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "postgres-setup"
path = "src/bin/postgres-setup.rs"

[[bin]]
name = "postgres-teardown"
path = "src/bin/postgres-teardown.rs"

[dependencies]
turul-mcp-server = { path = "../../crates/turul-mcp-server", features = ["http", "sse"] }
turul-mcp-session-storage = { path = "../../crates/turul-mcp-session-storage", features = ["postgres"] }
turul-mcp-derive = { path = "../../crates/turul-mcp-derive" }
turul-mcp-protocol = { path = "../../crates/turul-mcp-protocol" }

tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"

[features]
default = []