[package]
name = "simple-postgres-session"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "simple-postgres-session"
path = "src/main.rs"

[[bin]]
name = "postgres-setup"
path = "src/bin/postgres-setup.rs"

[[bin]]
name = "postgres-teardown"
path = "src/bin/postgres-teardown.rs"


[dependencies]
turul-mcp-server = { workspace = true, features = ["http", "sse", "postgres"] }
turul-mcp-session-storage = { workspace = true, features = ["postgres"] }
turul-mcp-derive.workspace = true
turul-mcp-builders.workspace = true
turul-mcp-protocol.workspace = true

tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
chrono.workspace = true
async-trait.workspace = true
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-rustls"] }
url = "2.4"

[features]
default = []