[package]
name = "resource-macro-example"
version = "0.1.0"
edition.workspace = true

[dependencies]
turul-mcp-derive = { workspace = true }
turul-mcp-server = { workspace = true }
turul-mcp-protocol = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }