[package]
name = "completion-server"
version = "0.2.2"
edition.workspace = true

[dependencies]
turul-mcp-server.workspace = true
turul-mcp-protocol.workspace = true
turul-mcp-builders.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
async-trait.workspace = true