#!/bin/bash
# Quick manual test for middleware examples

echo "Manual Middleware Example Testing"
echo "=================================="
echo ""
echo "1. Logging Server (Port 8080)"
echo "   cargo run --package middleware-logging-server"
echo "   - Logs request start/completion with timing"
echo "   - No authentication required"
echo ""
echo "2. Rate Limit Server (Port 8080)"
echo "   cargo run --package middleware-rate-limit-server"
echo "   - Allows 5 requests per session"
echo "   - 6th request returns error -32003 (RateLimitExceeded)"
echo ""
echo "3. Auth Server (Port 8080)"
echo "   cargo run --package middleware-auth-server"
echo "   - Requires X-API-Key header"
echo "   - Valid keys: secret-key-123 (user-alice), secret-key-456 (user-bob)"
echo "   - Call 'whoami' tool to see authenticated user"
echo ""
echo "Test commands:"
echo ""
echo "# Initialize"
echo "curl -X POST http://localhost:8080/mcp \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Accept: application/json' \\"
echo "  -H 'X-API-Key: secret-key-123' \\"
echo "  -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"2025-06-18\",\"capabilities\":{},\"clientInfo\":{\"name\":\"test\",\"version\":\"1.0\"}}}' | jq"
echo ""
echo "# Call whoami tool (auth server only)"
echo "SESSION_ID=<from-init-response>"
echo "curl -X POST http://localhost:8080/mcp \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Accept: application/json' \\"
echo "  -H 'X-API-Key: secret-key-123' \\"
echo "  -H \"Mcp-Session-Id: \$SESSION_ID\" \\"
echo "  -d '{\"jsonrpc\":\"2.0\",\"method\":\"notifications/initialized\"}'"
echo ""
echo "curl -X POST http://localhost:8080/mcp \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Accept: application/json' \\"
echo "  -H 'X-API-Key: secret-key-123' \\"
echo "  -H \"Mcp-Session-Id: \$SESSION_ID\" \\"
echo "  -d '{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"whoami\",\"arguments\":{}}}' | jq"
echo ""
