[package]
name = "session-logging-proof-test"
version = "0.2.2"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
turul-mcp-server.workspace = true
turul-mcp-protocol.workspace = true
turul-mcp-builders.workspace = true
turul-mcp-session-storage.workspace = true
anyhow.workspace = true
async-trait.workspace = true
reqwest.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true