[package]
name = "simple-resources-demo"
version = "0.2.2"
edition = "2021"

[workspace]

[dependencies]
turul-mcp-server = { path = "../../crates/turul-mcp-server" }
turul-mcp-protocol = { path = "../../crates/turul-mcp-protocol" }
turul-mcp-derive = { path = "../../crates/turul-mcp-derive" }
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }

[[bin]]
name = "simple-resources-demo"
path = "src/main.rs"